// Source: "2026 Affordable Housing Bond Issuances" Google Sheet (Sheet1).
// lat/lng converted from POINT_X/POINT_Y (Web Mercator, EPSG:3857).
// `neighborhood` is the SF realtor neighborhood the point falls inside (point-in-polygon).

export const BOND_PROJECTS = [
  {"id": 1, "project": "Treasure Island E1.2 Senior", "program": "2019 Affordable Housing Bond", "proposition": "Prop. A (2019)", "category": "Senior Housing", "status": "Predevelopment", "units": 100, "completion": "9/1/2027", "district": 6, "supervisor": "Matt Dorsey", "neighborhood": "Treasure Island", "lat": 37.820937, "lng": -122.366194, "blurb": "Treasure Island E1.2 Senior received $29 million in funds from 2019's Proposition A to finance senior housing. The building will have 100 units and is estimated to be completed by mid-2027."},
  {"id": 2, "project": "Freedom West Senior", "program": "2019 Affordable Housing Bond", "proposition": "Prop. A (2019)", "category": "Senior Housing", "status": "Predevelopment", "units": 115, "completion": "9/1/2027", "district": 5, "supervisor": "Bilal Mahmood", "neighborhood": "Western Addition", "lat": 37.779501, "lng": -122.426535, "blurb": "The Freedom West senior building received $18 million in funds from 2019's Proposition A to finance senior housing. The building will have 115 units and is expected to be completed by mid-2027. This project is part of the larger Freedom West Coop revitalization project."},
  {"id": 3, "project": "1939 Market", "program": "2019 Affordable Housing Bond", "proposition": "Prop. A (2019)", "category": "Senior Housing", "status": "Predevelopment", "units": 187, "completion": "9/1/2027", "district": 8, "supervisor": "Rafael Mandelman", "neighborhood": "Mission Dolores", "lat": 37.769893, "lng": -122.425529, "blurb": "1939 Market received approximately $17.5 million in funds from 2019's Proposition A to finance senior housing. The project also received $19 million in funds from 2024's Proposition A to finance low-income housing. Funds from both bonds will support 175 units of affordable housing."},
  {"id": 4, "project": "772 Pacific", "program": "2019 Affordable Housing Bond", "proposition": "Prop. A (2019)", "category": "Senior Housing", "status": "Predevelopment", "units": 175, "completion": "3/1/2028", "district": 3, "supervisor": "Danny Sauter", "neighborhood": "Financial District/Barbary Coast", "lat": 37.79701, "lng": -122.40802, "blurb": "772 Pacific received $35 million in funds from 2019's Proposition A to finance senior housing. The building will have 175 affordable units and is estimated to be completed by mid-2028."},
  {"id": 5, "project": "Treasure Island IC4.3", "program": "2024 Affordable Housing Bond", "proposition": "Prop. A (2024)", "category": "Low-Income Housing", "status": "Predevelopment", "units": 150, "completion": "9/1/2027", "district": 6, "supervisor": "Matt Dorsey", "neighborhood": "Treasure Island", "lat": 37.819898, "lng": -122.369335, "blurb": "Treasure Island IC4.3 received $25 million in funds from 2024's Proposition A to finance low-income housing. The building will have 150 units and is estimated to be completed by mid-2027."},
  {"id": 6, "project": "1939 Market", "program": "2024 Affordable Housing Bond", "proposition": "Prop. A (2024)", "category": "Low-Income Housing", "status": "Predevelopment", "units": 187, "completion": "9/1/2027", "district": 8, "supervisor": "Rafael Mandelman", "neighborhood": "Mission Dolores", "lat": 37.769884, "lng": -122.425513, "blurb": "1939 Market received approximately $17.5 million in funds from 2019's Proposition A to finance senior housing. The project also received $19 million in funds from 2024's Proposition A to finance low-income housing. Funds from both bonds will support 175 units of affordable housing."},
  {"id": 7, "project": "Derek Silva Community", "program": "2016 PASS Bond", "proposition": "Prop. C (2016)", "category": "Affordable Housing Rehabilitation", "status": "Committed", "units": 80, "completion": "3/1/2029", "district": 6, "supervisor": "Matt Dorsey", "neighborhood": "Van Ness/Civic Center", "lat": 37.774499, "lng": -122.420541, "blurb": "Derek Silva Community received almost $10 million in funds from 2016's Proposition C for building rehabilitation. The building has 85 units, 68 of which are affordable. The funds will be used for a major seismic retrofit, unit improvements, and plumbing, waterproofing, and electrical issues."},
  {"id": 8, "project": "Altamont", "program": "2016 PASS Bond", "proposition": "Prop. C (2016)", "category": "Affordable Housing Rehabilitation", "status": "Prospect", "units": 89, "completion": "3/1/2030", "district": 9, "supervisor": "Jackie Fielder", "neighborhood": "Inner Mission", "lat": 37.765207, "lng": -122.42069, "blurb": "Altamont received approximately $5 million in funds from 2016's Proposition C to rehabilitation at-risk housing. The building has 88 affordable units for residents who were formerly homeless and very low-income adults."},
  {"id": 9, "project": "2059 Mission", "program": "2016 PASS Bond", "proposition": "Prop. C (2016)", "category": "Affordable Housing Rehabilitation", "status": "Committed", "units": 31, "completion": "12/1/2028", "district": 9, "supervisor": "Jackie Fielder", "neighborhood": "Inner Mission", "lat": 37.76404, "lng": -122.419311, "blurb": "2059 Mission received almost $10 million in funds from 2016's Proposition C to acquire the property and convert it to affordable housing. The building has 31 units, and the conversion is expected to be completed by the end of 2028."},
  {"id": 10, "project": "Rich Sorro", "program": "2016 PASS Bond", "proposition": "Prop. C (2016)", "category": "Affordable Housing Rehabilitation", "status": "Prospect", "units": 100, "completion": "2/1/2029", "district": 6, "supervisor": "Matt Dorsey", "neighborhood": "South Beach", "lat": 37.777177, "lng": -122.391729, "blurb": "Rich Sorro Commons received approximately $14.5 million in funds from 2016's Proposition C to rehabilitate at-risk housing. The building has 100 affordable units and work on the building is expected to be complete by 2029."},
];
